  name: rem
  version: '0.13.1-dev'
  summary: rem is a small tool for remembering things on the command line.
  description: |
    rem is a small tool for remembering things on the command line. It can
    be used to store commands and execute them later on. Or to simply store
    lines of text.

  base: core20
  grade: devel
  confinement: classic

  architectures:
    - build-on: [amd64, i386, armhf]
      run-on: [amd64, i386, armhf]

  apps:
    rem:
      command: bin/rem

  parts:
    rem:
      source: https://github.com/mborho/rem.git
      source-branch: master
      plugin: go
      go-buildtags: [core]
