  name: rem
  version: '0.13.1-dev'
  summary: rem is a small tool for remembering things on the command line.
  description: |
    rem is a small tool for remembering things on the command line. It can
    be used to store commands and execute them later on. Or to simply store
    lines of text.

  grade: stable
  confinement: classic

  apps:
    rem:
      command: bin/rem

  parts:
    rem:
      source: https://github.com/mborho/rem.git
      source-tag: master
      go-importpath: github.com/mborho/rem
      plugin: go
      go-packages: [github.com/mborho/rem]
      go-buildtags: [core]
      after: [go]
    go:
      source-tag: go1.8
