  name: rem
  version: '0.10.0'
  summary: rem is a small tool for remembering things on the command line.
  description: |
    rem is a small tool for remembering things on the command line. It can
    be used to store commands and execute them later on. Or to simply store
    lines of text.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    rem:
      command: rem
  parts:
    rem:
      plugin: go
